<?php

namespace NotificationBundle\Repository;

/**
 * CampanyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CampanyRepository extends \Doctrine\ORM\EntityRepository
{
}
