<?php

namespace NotificationBundle\Repository;

/**
 * FollowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FollowRepository extends \Doctrine\ORM\EntityRepository
{

    //public function findAllfollow(){
        /* $qb=$this->getEntityManager()->createQueryBuilder()
             ->select('c')
             ->from($this->_entityName,'c');
         $query=$qb->getQuery();*/
       // $query=$this->getEntityManager()
          //  ->createQuery("select co.nameCampany from NotificationBundle: campany co ,NotificationBundle: Follow f
          // where f.campany = co.idcampany");
      //  return $results=$query->getResult();
  //  }
    public function getfollowbynamecampany($name){

        $query=$this->getEntityManager()->createQuery(
            "select c.nameCampany,from NotificationBundle: campany c, NotificationBundle: Follow f
            where  f.campany = c.idcampany and c.nameCampany='".$name."'");

        return $query->getResult();
    }





}
