<?php

namespace NotificationBundle\Repository;

/**
 * PostCandiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostCandiRepository extends \Doctrine\ORM\EntityRepository
{
}
