<?php

namespace NotificationBundle\Repository;

/**
 * PostCampRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostCampRepository extends \Doctrine\ORM\EntityRepository
{
}
