<?php

namespace NotificationBundle\Repository;

/**
 * samediRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class samediRepository extends \Doctrine\ORM\EntityRepository
{
}
